services:
  incubapp:
    build: .
    ports:
      - "80:80"
    restart: always
    environment:
      - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
      - VITE_SUPABASE_KEY=${VITE_SUPABASE_KEY}
    networks:
      - app-network
      - supabase_default

  # Ngrok container to expose the application to the internet
  ngrok:
    image: ngrok/ngrok:latest
    restart: always
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
    command:
      - "http"
      - "incubapp:80"
    ports:
      - "4040:4040"
    networks:
      - app-network
    depends_on:
      - incubapp

networks:
  app-network:
    driver: bridge
  supabase_default:
    external: true
